"""Rebuild the trading-edge registry from the committed research evidence.

    python scripts/edge_registry.py      # -> research/knowledge/edge_registry.json
                                         #    docs/TRADING_EDGE_REGISTRY.md

Read-only over the evidence; both outputs are derived and can be regenerated at any time.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from aitrader.research.discovery.edges import build  # noqa: E402

HEADER = """# Trading edge registry

Generated by `python scripts/edge_registry.py` from the committed evidence
(`research/knowledge/*.json`, `research/results/WF-*.json`, `research/discovery/ledger.jsonl`).
Do not edit by hand; the machine-readable form is `research/knowledge/edge_registry.json`.

Every judged hypothesis is one record. A number the evidence does not contain is shown as —
(gross expectancy, profit factor and drawdown are not recorded per hypothesis by the
confirmatory battery), never estimated. Net and out-of-sample expectancy are in R per trade
after all costs; "cost ×1.5" is the same trades with spread and swap x1.5 and slippage x2.

Lifecycle: DISCOVERED -> VALIDATING -> VALIDATED -> DEGRADED -> RETIRED, or REJECTED. REJECTED
and RETIRED are final. Only a person promotes a VALIDATED edge, into
`models/artifacts/promoted_edges.json`, after the holdout.

PR-001 and the archive trials predate per-hypothesis artifacts; they are in
[EXPERIMENT_LOG.md](EXPERIMENT_LOG.md). Walk-forward trials still running appear once their
result is committed.
"""


def _f(x, nd=3):
    return "—" if x is None else (f"{x:+.{nd}f}" if isinstance(x, float) else str(x))


def markdown(reg: dict) -> str:
    c = reg["counts"]
    lines = [HEADER, "## Summary", "",
             " | ".join(f"{k} {v}" for k, v in c.items()), "",
             "## Programs", "", "| Program | Verdict | Screened | Judged | Validated | Threshold t |",
             "|---|---|---|---|---|---|"]
    for k, p in sorted(reg["programs"].items()):
        thr = p.get("threshold_t")
        lines.append(f"| {k} | {p['verdict']} | {p.get('screened', '—')} | {p.get('judged', '—')} | "
                     f"{len(p.get('validated') or [])} | {thr:.3f} |" if thr else
                     f"| {k} | {p['verdict']} | {p.get('screened', '—')} | {p.get('judged', '—')} | "
                     f"{len(p.get('validated') or [])} | — |")
    lines += ["", "## Edges", "",
              "| Edge | Side | TF | Entry | Exit | n | Net R | t (required) | Cost ×1.5 | Walk-fwd R | "
              "Complexity | Status | Failed checks |",
              "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for e in reg["edges"]:
        req = f"{e['t_stat']:+.2f} ({e['t_required']:.2f})" if e["t_stat"] is not None and e["t_required"] else "—"
        lines.append(f"| {e['edge_id']} | {e['direction']} | {e['timeframe'] or '—'} | `{e['entry_conditions']}` | "
                     f"{e['exit_conditions']} | {_f(e['sample_size'])} | {_f(e['net_expectancy'])} | {req} | "
                     f"{_f(e['cost_sensitivity'])} | {_f(e['walk_forward_expectancy'])} | {e['complexity']} | "
                     f"**{e['status']}** | {', '.join(e['failed_checks']) or '—'} |")
        if e.get("note"):
            lines.append(f"| ↳ correction | | | {e['note']} | | | | | | | | | |")
    return "\n".join(lines) + "\n"


def main() -> int:
    reg = build(ROOT / "research")
    (ROOT / "research" / "knowledge" / "edge_registry.json").write_text(json.dumps(reg, indent=1, sort_keys=True) + "\n")
    (ROOT / "docs" / "TRADING_EDGE_REGISTRY.md").write_text(markdown(reg))
    print(json.dumps(reg["counts"]), {k: v["verdict"] for k, v in reg["programs"].items()})
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
