"""Mutation audit: remove each safety guard in turn and require a test to fail.

    python scripts/mutation_audit.py            # writes docs/MUTATION_AUDIT.md

A guard whose removal no test notices is a guard nobody is checking
(docs/TESTING_PHILOSOPHY.md). Each mutant replaces one exact snippet; the
file is restored whatever happens. A mutant whose snippet is not found is
reported as STALE, never skipped silently.
"""

from __future__ import annotations

import os
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# (id, guard, file, original, mutant, tests)
MUTANTS = [
    ("risk-ceiling", "per-trade risk is clamped to the hard ceiling",
     "aitrader/risk/engine.py", "pct = min(self.risk_per_trade_pct, HARD_MAX_RISK_PCT, UNVALIDATED_MAX_RISK_PCT)",
     "pct = self.risk_per_trade_pct", ["tests/unit/test_risk.py"]),
    ("risk-streak", "risk only ever decreases after losses",
     "aitrader/risk/engine.py", "return max(floor_, 0.5 ** (run // step)) if step > 0 else 1.0",
     "return 1.0", ["tests/unit/test_risk.py"]),
    ("risk-drawdown", "maximum drawdown halts trading",
     "aitrader/risk/engine.py", 'Check("drawdown", dd > -max_dd,', 'Check("drawdown", True,',
     ["tests/unit/test_risk.py"]),
    ("exec-killswitch", "an unreadable kill switch counts as active",
     "aitrader/execution/engine.py", 'if not isinstance(ks, dict) or ks.get("active") is not False:',
     'if isinstance(ks, dict) and ks.get("active") is True:', ["tests/unit/test_execution.py"]),
    ("exec-demo", "no order unless the account is positively verified demo/paper",
     "aitrader/execution/engine.py", "if demo is not True:",
     "if demo is False:", ["tests/unit/test_execution.py", "tests/unit/test_experimental_ai.py"]),
    ("exec-no-resend", "an ambiguous write is resolved by query, never resent",
     "aitrader/execution/engine.py",
     '            self._set_status(cid, "UNKNOWN", {"reason": str(exc)})\n            found = self._lookup(cid)',
     '            self._set_status(cid, "UNKNOWN", {"reason": str(exc)})\n'
     '            self.broker.place_market(decision.instrument, side, verdict.qty, verdict.stop, verdict.target,'
     ' cid + "-retry", meta=meta or {})\n            found = self._lookup(cid)',
     ["tests/unit/test_execution.py"]),
    ("exec-stale-price", "no order when the live price is already beyond the stop",
     "aitrader/execution/engine.py", "if (live - verdict.stop) * side <= 0:", "if False:",
     ["tests/unit/test_execution.py"]),
    ("demo-name", "an account NAME can fail the demo check but never pass it",
     "aitrader/broker/tradelocker/demo_guard.py",
     "    for field, raw in names:\n        text = str(raw).strip().lower()",
     "    candidates.extend(names)\n    for field, raw in names:\n        text = str(raw).strip().lower()",
     ["tests/unit/test_tradelocker_adapter.py"]),
    ("live-refused", "MODE=LIVE is refused at startup, with its own reason",
     "aitrader/service/config.py", 'if mode == "LIVE":', 'if mode == "NEVER":',
     ["tests/integration/test_service.py"]),
    ("live-both-layers", "MODE=LIVE is refused even if the allow-list were widened",
     "aitrader/service/config.py", ['if mode == "LIVE":', 'if mode not in ("PAPER", "DEMO"):'],
     ['if mode == "NEVER":', 'if mode not in ("PAPER", "DEMO", "LIVE"):'],
     ["tests/integration/test_service.py"]),
    ("token", "resume / clear / scan / revert need the dashboard token",
     "aitrader/service/server.py", "if given and hmac.compare_digest(given.encode(), token.encode()):",
     "if True:", ["tests/integration/test_service.py"]),
    ("knowledge-hash", "the knowledge base loads only if it matches its card",
     "aitrader/service/runtime.py", 'if digest != meta.get("sha256"):', "if False:",
     ["tests/integration/test_service.py"]),
    ("cycle-lock", "cycles, scans and bar monitoring never run concurrently",
     "aitrader/service/runtime.py", "        with self._cycle_lock:\n            return self._run_cycle_locked(",
     "        if True:\n            return self._run_cycle_locked(", ["tests/integration/test_service.py"]),
    ("revert-append-only", "a knowledge revert is a new, higher version; numbers are never reused",
     "aitrader/orchestrator/core.py", "self.knowledge_version = max(latest, parent) + 1",
     "self.knowledge_version = parent + 1 if not extra else extra.get('revert_to', parent) + 1",
     ["tests/integration/test_service.py"]),
    ("shadow-journal", "skipped candidates' outcomes are journalled for restart",
     "aitrader/orchestrator/core.py", 'if shadows and self.cfg.journal == "full":', "if False:",
     ["tests/integration/test_pipeline.py"]),
    ("log-redaction", "secret environment values never reach a log line",
     "aitrader/observability.py", "    for secret in _secret_values():", "    for secret in []:",
     ["tests/unit/test_observability.py"]),
    ("learning-overlap", "overlapping outcomes are not counted as independent evidence",
     "aitrader/learning/experience.py", "        return overlap * max(1.0, self.n / max(1, uniq))", "        return 1.0",
     ["tests/unit/test_learning.py"]),
    ("lab-register-first", "nothing is evaluated before it is registered",
     "aitrader/research/lab.py", '            raise LabError(f"{trial_id} is not registered: nothing is evaluated before it is") from None',
     '            trial = None', ["tests/unit/test_research_lab.py"]),
    ("lab-no-rescue", "a failed hypothesis cannot be re-run with a new threshold or dates",
     "aitrader/research/lab.py", 'if t.design.get("substance") == spec.substance() and self.registry.status_of(t.id) == "FAILED":',
     'if False:', ["tests/unit/test_research_lab.py"]),
    ("lab-llm-cutoff", "a language-model hypothesis is never judged on data the model may have read",
     "aitrader/research/lab.py", "            if spec.fit_start < spec.llm_cutoff:", "            if False:", ["tests/unit/test_research_lab.py"]),
    ("lab-holdout", "the lab never touches the sealed holdout",
     "aitrader/research/lab.py", "        if h is not None and h.universe == spec.universe and spec.judge_end > h.start:",
     "        if False:", ["tests/unit/test_research_lab.py"]),
    ("lab-isolation", "the lab never writes where production loads",
     "aitrader/research/lab.py", "        if self.artifacts_dir == PRODUCTION_ARTIFACTS or PRODUCTION_ARTIFACTS in self.artifacts_dir.parents:",
     "        if False:", ["tests/unit/test_research_lab.py"]),
    ("lab-purge", "walk-forward trains only on outcomes resolved before the fold (minus an embargo)",
     "aitrader/research/lab.py", "(rt >= 0) & (rt < f0 - embargo) & np.isfinite(y)", "(rt >= 0) & np.isfinite(y)", ["tests/unit/test_research_lab.py"]),
    ("lab-scan-overlap", "the scan counts only non-overlapping outcomes",
     "aitrader/research/lab.py", "            ok &= _non_overlapping(t, rt, sym)", "            pass", ["tests/unit/test_research_lab.py"]),
    ("feature-leakage-gate", "a leaky candidate feature is rejected before evaluation",
     "aitrader/research/features_lab.py", '"status": "ELIGIBLE" if not bad else "REJECTED_LEAKAGE"',
     '"status": "ELIGIBLE"', ["tests/unit/test_research_lab.py"]),
    ("boundary-imports", "research code cannot import the broker or execution",
     "aitrader/research/lab.py", "from .models import MODEL_FAMILIES, MODELS_VERSION",
     "from .models import MODEL_FAMILIES, MODELS_VERSION\nfrom ..broker.paper import PaperBroker  # noqa: F401",
     ["tests/unit/test_architecture.py"]),
    ("boundary-sizing", "only the risk engine computes a position size",
     "aitrader/decision/synthesis.py", "        cand, required, conf, contra = best_decision",
     "        cand, required, conf, contra = best_decision\n        qty = 1.0  # noqa: F841",
     ["tests/unit/test_architecture.py"]),
    ("llm-trader-side", "a model trade with its stop or target on the wrong side is refused",
     "aitrader/agents/llm_trader.py", "    if (entry - stop) * side <= 0 or (target - entry) * side <= 0:", "    if False:", ["tests/unit/test_llm_trader.py", "tests/unit/test_trading_room.py"]),
    ("llm-trader-block-first", "a market-wide block stops the decision before the model is consulted",
     "aitrader/agents/llm_trader.py", "    if blocking:\n        return (\"blocked before consulting the model", "    if False:\n        return (\"blocked before consulting the model", ["tests/unit/test_llm_trader.py", "tests/unit/test_trading_room.py"]),
    ("llm-trader-paused", "while paused or stopped the model is not consulted",
     "aitrader/agents/llm_trader.py", "    if not ctx.trading_allowed:", "    if False:", ["tests/unit/test_llm_trader.py", "tests/unit/test_trading_room.py"]),
    ("llm-trader-no-backtest", "the model trader refuses to be backtested",
     "aitrader/agents/llm_trader.py", '        if ctx.mode == "BACKTEST":', "        if False:", ["tests/unit/test_llm_trader.py"]),
    ("llm-trader-stop-distance", "an absurdly far stop (a typo) is refused",
     "aitrader/agents/llm_trader.py", "    if dist > MAX_STOP_ATR:", "    if False:", ["tests/unit/test_llm_trader.py", "tests/unit/test_trading_room.py"]),
    ("llm-trader-lesson", "a validated lesson about its own trades blocks the repeat",
     "aitrader/agents/llm_trader.py", "        if hits:", "        if False:", ["tests/unit/test_llm_trader.py", "tests/unit/test_trading_room.py"]),
    ("llm-view-not-veto", "the quant system's view of the market is information to the model, not a veto",
     "aitrader/agents/llm_trader.py", " and not o.data.get(\"action\") and o.code in PRE_MODEL_BLOCKS]",
     " and not o.data.get(\"action\")]", ["tests/unit/test_llm_trader.py", "tests/unit/test_trading_room.py"]),
    ("provider-failover", "when a provider fails, the next provider answers",
     "aitrader/llm/provider.py", "        for ep in endpoints:", "        for ep in endpoints[:1]:",
     ["tests/unit/test_llm_providers.py"]),
    ("provider-key-redaction", "every *_API_KEY variable is redacted from logs",
     "aitrader/observability.py", "        if key in SECRET_ENV_KEYS or _SECRET_NAME.search(key):",
     "        if key in SECRET_ENV_KEYS:", ["tests/unit/test_llm_providers.py"]),
    ("cadence-evidence-refused", "the evidence system refuses a decision cadence it was never tested at",
     "aitrader/service/runtime.py", "if cfg.decision_interval_min and self.orch.brain.config.decision_mode not in FLEX_MODES:",
     "if False:", ["tests/integration/test_cadence.py"]),
    ("cadence-rotation", "pairs rotate so every pair is analysed in turn",
     "aitrader/service/runtime.py", "        self._rotation = (self._rotation + k) % len(syms)\n", "", ["tests/integration/test_cadence.py"]),
    ("paper-preopen-bar", "a bar from before a position opened never closes it",
     "aitrader/broker/paper.py", 'if p["symbol"] != symbol or p["opened"] > bar["open_time"]:',
     'if p["symbol"] != symbol:', ["tests/integration/test_cadence.py"]),
    ("fast-monitor", "open paper positions are checked on M1 bars between H1 closes",
     "aitrader/service/runtime.py", "        self._monitor_fast(now)\n", "", ["tests/integration/test_cadence.py"]),
    ("market-row-isolation", "one pair's failed price does not blank the pairs table",
     "aitrader/service/runtime.py", "            except Exception as exc:\n                q, q_err = None,",
     "            except ZeroDivisionError as exc:\n                q, q_err = None,", ["tests/integration/test_cadence.py"]),
    ("calendar-unknown-not-empty", "an unreachable calendar is reported as unknown, never as no events",
     "aitrader/data/calendar.py", "out[\"events\"] = None  # unknown, not \"none\"", "out[\"events\"] = []",
     ["tests/unit/test_calendar.py"]),
    ("calendar-rate-limit", "the calendar is downloaded at most hourly",
     "aitrader/data/calendar.py", "if self._fetched_at is not None and now - self._fetched_at < REFRESH_S:",
     "if False:", ["tests/unit/test_calendar.py"]),
    ("room-roles", "each mind is told its role in the team",
     "aitrader/agents/trading_room.py", "role = \" AND \".join(f\"{r}, {desc[r]}\" for r in roles[m])",
     "role = \"any\"", ["tests/unit/test_trading_room.py"]),
    ("history-integrity", "the history memory loads only if it matches its card",
     "aitrader/service/runtime.py", "            if digest == meta.get(\"sha256\"):\n                desk = HistoryDesk(",
     "            if True:\n                desk = HistoryDesk(", ["tests/unit/test_history_desk.py"]),
    ("history-episodes", "overlapping hours are not counted as independent evidence",
     "aitrader/memory/history.py", "* (ev.k / max(1, ev.distinct_episodes or ev.k)) ** 0.5", "* 1.0",
     ["tests/unit/test_history_desk.py"]),
    ("review-closes", "the model closes its open trade when it decides to",
     "aitrader/orchestrator/core.py", "            if verdict and verdict[\"action\"] == \"CLOSE\":",
     "            if False:", ["tests/integration/test_cadence.py"]),
    ("review-only-close", "a review can only hold or close; anything else holds",
     "aitrader/agents/llm_trader.py", "    if d.get(\"action\") not in (\"HOLD\", \"CLOSE\"):\n        return \"action must be HOLD or CLOSE\"",
     "    if False:\n        return \"action must be HOLD or CLOSE\"", ["tests/integration/test_cadence.py"]),
    ("review-paused", "no position is reviewed while trading is paused",
     "aitrader/orchestrator/core.py", "        if reviewer is None or not self._trading_allowed():", "        if reviewer is None:", ["tests/integration/test_cadence.py"]),
    ("minute-time-exit", "a holding time of minutes is honoured between cycles",
     "aitrader/service/runtime.py", "        self.orch.time_exits(now)  # a holding time", "        pass  # a holding time", ["tests/integration/test_cadence.py"]),
    ("review-by-turn", "an open trade is reviewed on its own pair's turn, not every cycle",
     "aitrader/orchestrator/core.py", "            if symbols is not None and row[\"symbol\"] not in symbols:\n                continue",
     "            if False:\n                continue", ["tests/integration/test_cadence.py"]),
    ("history-per-timeframe", "a failing timeframe never erases the history shape another learned",
     "aitrader/broker/tradelocker/history.py", "            self.reset(tf)\n", "            self.reset()\n",
     ["tests/unit/test_history_fetcher.py"]),
    ("history-cooldown", "a timeframe the broker does not serve is not re-probed until the cooldown ends",
     "aitrader/broker/tradelocker/history.py", "        if known is None and blocked:", "        if False:",
     ["tests/unit/test_history_fetcher.py"]),
    ("data-state-honest", "quotes without bars are reported as such, never as CONNECTED",
     "aitrader/service/runtime.py", "        if bars_ok == \"n/a\" or (bars_ok and now - bars_ok < 3 * 3600):",
     "        if True:", ["tests/integration/test_cadence.py"]),
    ("yahoo-forming-bar", "a forming Yahoo bar is never used",
     "aitrader/data/yahoo.py", "        ok &= t + PERIOD_S[tf] <= as_of", "        ok &= t > 0", ["tests/unit/test_yahoo_feed.py"]),
    ("yahoo-quote-own-time", "a Yahoo price carries Yahoo's time, not the time it was fetched",
     "aitrader/data/yahoo.py", "float(px) + half, int(at))", "float(px) + half, int(t))", ["tests/unit/test_yahoo_feed.py"]),
    ("source-unavailable-features", "a feature the source never provides is excluded, not treated as missing data",
     "aitrader/orchestrator/core.py", "        if absent and any(m in absent for m in fv.missing):", "        if False:", ["tests/unit/test_yahoo_feed.py"]),
    ("strict-json", "every response is strict JSON: a NaN becomes null, never an unparseable NaN",
     "aitrader/service/server.py", "json.dumps(_finite(body), default=str, allow_nan=False)", "json.dumps(body, default=str)",
     ["tests/integration/test_service.py"]),
    ("monitor-no-gap", "a stop hit while the team deliberated is still applied",
     "aitrader/service/runtime.py", 'bars = self.feed.bars_tf(s, "M1", now, 60)', 'bars = self.feed.bars_tf(s, "M1", now, 5)',
     ["tests/integration/test_cadence.py"]),
    ("model-not-asked-when-refused", "no model call for a trade the risk engine's account checks already refuse",
     "aitrader/agents/llm_trader.py", "    if ctx.account_blocks:\n", "    if False:\n",
     ["tests/integration/test_cadence.py"]),
    ("account-gates-complete", "the pre-model account checks include every position limit evaluate() applies",
     "aitrader/risk/engine.py", "        out += self._c_positions(account, instrument)\n", "",
     ["tests/unit/test_risk.py", "tests/integration/test_cadence.py"]),
    ("time-exit-label", "a holding-time exit is recorded as TIME",
     "aitrader/execution/engine.py", 'if reason in ("MODEL_EXIT", "TIME") else', 'if reason == "MODEL_EXIT" else',
     ["tests/integration/test_cadence.py"]),
    ("llm-user-agent", "model requests carry their own User-Agent (Cloudflare refuses Python's default)",
     "aitrader/llm/provider.py", '"Content-Type": "application/json", "User-Agent": USER_AGENT}',
     '"Content-Type": "application/json"}', ["tests/unit/test_llm_providers.py"]),
    ("llm-rest-after-refusal", "a model refused for quota or an unknown name rests instead of being asked every minute",
     "aitrader/llm/provider.py", "                self._after(label, last)\n", "", ["tests/unit/test_llm_providers.py"]),
    ("memory-atomic-save", "the live memory is written beside the target and swapped in whole",
     "aitrader/memory/patterns.py", "        os.replace(tmp, path)\n", "        os.replace(tmp, path)\n        path.write_bytes(b'PK')\n",
     ["tests/integration/test_service.py"]),
    ("map-swing-confirmed", "a swing exists only once the bars after it have closed",
     "aitrader/features/market_map.py", "and h[i] >= h[i + 1:i + k + 1].max()]", "]",
     ["tests/unit/test_market_map.py"]),
    ("map-fvg-walk-forward", "a fair value gap that price traded through is not reported",
     "aitrader/features/market_map.py", "        if status != \"filled\":\n", "        if True:\n",
     ["tests/unit/test_market_map.py"]),
    ("intermarket-completed", "intermarket context never uses a forming hour",
     "aitrader/data/yahoo.py", "ok = np.isfinite(c[:n]) & (t[:n] + 3600 <= as_of)", "ok = np.isfinite(c[:n])",
     ["tests/unit/test_yahoo_feed.py"]),
    ("desk-stop-first", "a bar touching both stop and target counts as the stop",
     "aitrader/features/strategy_desk.py", "                if hit_stop:  # stop first when a bar touches both",
     "                if hit_stop and not hit_target:  # stop first when a bar touches both",
     ["tests/unit/test_strategy_desk.py"]),
    ("desk-open-not-counted", "a trade still open at the last closed bar is not scored",
     "aitrader/features/strategy_desk.py", "            if r is not None:  # still open at the last completed bar: not counted\n                rs.append(r)",
     "            rs.append(r if r is not None else 0.0)", ["tests/unit/test_strategy_desk.py"]),
    ("desk-spread-paid", "the spread is paid on entry",
     "aitrader/features/strategy_desk.py", "entry = ac[i] if side > 0 else bc[i]", "entry = (ac[i] + bc[i]) / 2",
     ["tests/unit/test_strategy_desk.py"]),
    ("desk-breakout-causal", "the breakout level excludes the current bar",
     "aitrader/features/strategy_desk.py", '"dc20_hi": _prev(_roll(h, 20, np.max))', '"dc20_hi": _roll(h, 20, np.max)',
     ["tests/unit/test_strategy_desk.py"]),
    ("provider-failures-visible", "each AI provider's failures are counted and shown",
     "aitrader/llm/provider.py", "                self._note(ep.name, last)\n", "", ["tests/unit/test_llm_providers.py"]),
    ("room-own-voice", "a mind speaks only through its own provider",
     "aitrader/agents/trading_room.py", "|speak|{len(said)}\", only=m, shrink", "|speak|{len(said)}\", only=None, shrink", ["tests/unit/test_trading_room.py"]),
    ("room-hears-discussion", "each mind reads everything its teammates said before it",
     "aitrader/agents/trading_room.py", "{**packet, \"you\": m, \"discussion\": list(said)}",
     "{**packet, \"you\": m, \"discussion\": []}", ["tests/unit/test_trading_room.py"]),
    ("room-joint-checked", "the team's joint plan is checked and never repaired",
     "aitrader/agents/trading_room.py", "        problem = level_problem(ctx, p)\n        if problem:",
     "        problem = level_problem(ctx, p)\n        if False:", ["tests/unit/test_trading_room.py"]),
    ("room-nothing-seen", "when every mind sees nothing, no joint call is made",
     "aitrader/agents/trading_room.py", "if all(room[\"final\"][m][\"action\"] == \"NO_TRADE\" for m in present):",
     "if False:", ["tests/unit/test_trading_room.py"]),
    ("room-lesson", "a validated lesson blocks the team's trade",
     "aitrader/agents/trading_room.py", "hit = lesson_block(ctx, 1 if p[\"action\"] == \"BUY\" else -1)",
     "hit = None and lesson_block(ctx, 1 if p[\"action\"] == \"BUY\" else -1)", ["tests/unit/test_trading_room.py"]),
    ("holdout-loader", "the loader truncates at the sealed holdout without a key",
     "aitrader/data/store.py", "if self.holdout is not None and key is None:", "if False:",
     ["tests/unit/test_registry_and_store.py"]),
    ("holdout-single-use", "the final holdout answers one question, once",
     "aitrader/research/registry.py", "                if prior:\n                    raise HoldoutSpent(",
     "                if False:\n                    raise HoldoutSpent(", ["tests/unit/test_registry_and_store.py"]),
    ("memory-point-in-time", "an analogue counts only after its outcome resolved",
     "aitrader/memory/patterns.py", 'n_avail = int(np.searchsorted(avail, t, side="right"))',
     "n_avail = len(avail)", ["tests/unit/test_regime_and_patterns.py"]),
    ("label-stop-first", "stop and target in one bar resolve as the stop (labels)",
     "aitrader/research/labels.py", "tgt_hit = open_ & ~stop_hit & (hi >= target)",
     "tgt_hit = open_ & (hi >= target)", ["tests/unit/test_labels.py"]),
    ("paper-stop-first", "stop and target in one bar resolve as the stop (paper broker)",
     "aitrader/broker/paper.py",
     '                    if lo <= p["stop"]:\n                        closed.append(self._close(pid, min(op, p["stop"]) - slip, bar["close_time"], "STOP"))\n'
     '                    elif hi >= p["target"]:',
     '                    if hi >= p["target"]:\n                        closed.append(self._close(pid, p["target"], bar["close_time"], "TARGET"))\n'
     '                    elif lo <= p["stop"]:\n                        closed.append(self._close(pid, min(op, p["stop"]) - slip, bar["close_time"], "STOP"))\n'
     '                    elif False:',
     ["tests/unit/test_execution.py", "tests/integration/test_pipeline.py"]),
    ("synth-blocking", "a market-wide BLOCKING objection gives NO_TRADE before any candidate is weighed",
     "aitrader/decision/synthesis.py", '        if blocking:\n            return no_trade("blocked: "',
     '        if False:\n            return no_trade("blocked: "', ["tests/unit/test_agents.py"]),
    ("synth-blocking-both-layers", "a BLOCKING objection gives NO_TRADE (market-wide and per-candidate layers removed)",
     "aitrader/decision/synthesis.py",
     ['        if blocking:\n            return no_trade("blocked: "', "            if block:\n"],
     ['        if False:\n            return no_trade("blocked: "', "            if False:\n"],
     ["tests/unit/test_agents.py"]),
    ("reviewer-required", "a failed Reviewer (which carries lesson matching) gives NO_TRADE",
     "aitrader/decision/synthesis.py", 'REQUIRED_AGENTS = ("market", "setup", "risk", "adversary", "reviewer")',
     'REQUIRED_AGENTS = ("market", "setup", "risk", "adversary")', ["tests/unit/test_agents.py"]),
    ("synth-missing-agent", "a missing or failed agent gives NO_TRADE",
     "aitrader/decision/synthesis.py", "if r is None or not r.ok:", "if False:",
     ["tests/unit/test_agents.py"]),
    ("unfamiliar", "an unfamiliar market state blocks the trade",
     "aitrader/agents/analysts.py", "        if not rg.familiar:", "        if False:",
     ["tests/unit/test_agents.py", "tests/integration/test_pipeline.py"]),
    ("llm-vocabulary", "a model reply outside the closed objection vocabulary is discarded",
     "aitrader/agents/analysts.py", 'o.get("code") not in OBJECTION_CODES or ', "",
     ["tests/unit/test_agents.py"]),
    ("db-immutable", "episodic history cannot be updated or deleted",
     "aitrader/memory/db.py", "BEGIN SELECT RAISE(ABORT, '{table} is immutable history'); END",
     "BEGIN SELECT 1; END", ["tests/unit/test_db.py"]),
    ("price-scale", "an ambiguous price scale is refused, never guessed",
     "aitrader/data/instruments.py", "if len(fits) != 1:", "if not fits:", ["tests/unit/test_data.py"]),
    # the discovery engine (aitrader/research/discovery)
    ('disc-leakage-gate', 'only a feature that passed the truncation test may be used',
     'aitrader/research/discovery/catalog.py', '        if status != "PASSED":\n            raise LeakyFeature(',
     '        if False:\n            raise LeakyFeature(', ['tests/unit/test_discovery_catalog.py']),
    ('disc-feature-budget', 'a program cannot register more features than its declared budget',
     'aitrader/research/discovery/catalog.py', '        if used >= self._budgets[record.program]:',
     '        if False:', ['tests/unit/test_discovery_catalog.py']),
    ('disc-htf-closed', 'a higher-timeframe feature reads only buckets that have closed',
     'aitrader/research/discovery/primitives.py', 'k = np.searchsorted(h.available_at, s.available_at, side="right") - 1',
     'k = np.searchsorted(h.open_time, s.available_at, side="right") - 1', ['tests/unit/test_discovery_catalog.py']),
    ('disc-exit-stop-first', 'a bar touching stop and target is a stop (exit menu)',
     'aitrader/research/discovery/exits.py', '        open_ &= ~stop_hit\n        reach',
     '        reach', ['tests/unit/test_discovery_exits.py']),
    ('disc-purge', 'an outcome never straddles two segments',
     'aitrader/research/discovery/study.py', '    ok[ok] &= avail[last[ok]] <= t1\n',
     '', ['tests/unit/test_discovery_screen.py']),
    ('disc-one-position', 'one position per instrument: overlapping signals are not extra trades',
     'aitrader/research/discovery/study.py', '            pos = greedy(valid, o["free"])',
     '            pos = np.flatnonzero(valid)', ['tests/unit/test_discovery_screen.py']),
    ('disc-cluster', 'standard errors are clustered by week',
     'aitrader/research/discovery/stats.py', '    _, g = np.unique(np.asarray(clusters), return_inverse=True)',
     '    g = np.arange(n)', ['tests/unit/test_discovery_screen.py']),
    ('disc-fdr', 'a screen discovery needs Benjamini-Hochberg rejection, not just a positive mean',
     'aitrader/research/discovery/screen.py', 'r["discovery"] = bool(rej and r["testable"]',
     'r["discovery"] = bool(r["testable"]', ['tests/unit/test_discovery_screen.py']),
    ('disc-substance', 'a rejected idea cannot be drafted again under a new name',
     'aitrader/research/discovery/hypothesis.py', '            if st in ("REJECTED", "VALIDATED") and not (h.prospective_only and h.parent == other.id):',
     '            if False:', ['tests/unit/test_discovery_hypothesis.py']),
    ('disc-prospective', 'model and derived hypotheses are prospective only',
     'aitrader/research/discovery/hypothesis.py', '        if self.origin in ("llm", "derived") and not self.prospective_only:',
     '        if False:', ['tests/unit/test_discovery_hypothesis.py']),
    ('disc-no-size', 'a hypothesis never carries a position size',
     'aitrader/research/discovery/hypothesis.py', '            if f\'"{word}"\' in blob:',
     '            if False:', ['tests/unit/test_discovery_hypothesis.py']),
    ('disc-all-checks', 'VALIDATED needs every battery check, not only significance',
     'aitrader/research/discovery/battery.py', '"verdict": "VALIDATED" if not failed else "REJECTED"',
     '"verdict": "VALIDATED" if "significance" not in failed else "REJECTED"', ['tests/unit/test_discovery_battery.py']),
    ('disc-no-upgrade', 'the board can only subtract: a REJECTED result is never upgraded',
     'aitrader/research/discovery/board.py', 'verdict = "VALIDATED" if battery_verdict == "VALIDATED" and not blocked else "REJECTED"',
     'verdict = "VALIDATED" if not blocked else "REJECTED"', ['tests/unit/test_discovery_board.py']),
    ('disc-reviewer', 'the independent reviewer blocks a t-statistic it cannot reproduce',
     'aitrader/research/discovery/board.py', '    if sig["t"] is not None and (t_mine is None or abs(t_mine - sig["t"]) > 1e-3):',
     '    if False:', ['tests/unit/test_discovery_board.py']),
    ('disc-runs-once', 'a discovery program runs once',
     'aitrader/research/discovery/program.py', '        if self.registry.status_of(d.id) != "PENDING":\n            raise ProgramError(f"{d.id} already has a verdict ({',
     '        if False:\n            raise ProgramError(f"{d.id} already has a verdict ({', ['tests/unit/test_discovery_program.py']),
    ('disc-code-frozen', 'the code that runs is the code preregistered',
     'aitrader/research/discovery/program.py', '        if trial.design.get("code_sha256") != self.code_hash():',
     '        if False:', ['tests/unit/test_discovery_program.py']),
    ('disc-threshold', "the significance threshold is the registry's, counting every earlier test",
     'aitrader/research/discovery/program.py', '        if abs(need - d.rules.t_threshold) > 1e-9:\n            raise ProgramError(f"the design freezes t >= {d.rules.t_threshold:.4f} but',
     '        if False:\n            raise ProgramError(f"the design freezes t >= {d.rules.t_threshold:.4f} but', ['tests/unit/test_discovery_program.py']),
    ('disc-holdout', "a program's judged segment cannot reach the sealed holdout",
     'aitrader/research/discovery/program.py', '        if self.segments[2].end > self.holdout_start:',
     '        if False:', ['tests/unit/test_discovery_program.py']),
    ('disc-leak-prereg', 'a leaky feature stops preregistration',
     'aitrader/research/discovery/program.py', '        if failed:\n            raise ProgramError(f"leakage test failed',
     '        if False:\n            raise ProgramError(f"leakage test failed', ['tests/unit/test_discovery_program.py']),
    ('disc-isolation', 'research knowledge never goes where production loads models',
     'aitrader/research/discovery/program.py', '        if "models" in self.knowledge_dir.resolve().parts and "artifacts" in self.knowledge_dir.resolve().parts:',
     '        if False:', ['tests/unit/test_discovery_program.py']),
    ('disc-confirm-prospective', 'a prospective hypothesis is never judged on history older than itself',
     'aitrader/research/discovery/confirm.py', '                if self.design.fit.start < drafted or self.design.judge.start < drafted:',
     '                if False:', ['tests/unit/test_discovery_confirm.py']),
    # ── forward evidence, edge status, experimental AI (engineering audit 2026-10) ──
    ("exec-unvalidated", "an unvalidated trade is not executed unless that was enabled",
     "aitrader/execution/engine.py", 'if status != "VALIDATED" and not self.allow_unvalidated:', "if False:",
     ["tests/unit/test_experimental_ai.py"]),
    ("exec-stale-decision", "a stale decision is not executed",
     "aitrader/execution/engine.py", "if age > self.max_decision_age_s:", "if False:", ["tests/unit/test_experimental_ai.py"]),
    ("exec-entry-drift", "a price that ran away from the entry is not chased",
     "aitrader/execution/engine.py", "if drift > self.max_entry_drift_r:", "if False:", ["tests/unit/test_experimental_ai.py"]),
    ("live-trading-flag", "LIVE_TRADING=true is refused",
     "aitrader/service/config.py", 'if _flag(e, "LIVE_TRADING", False):', "if False:", ["tests/unit/test_experimental_ai.py"]),
    ("paper-mode-conflict", "PAPER_MODE contradicting MODE is refused",
     "aitrader/service/config.py", 'if pm and mode != "PAPER":', "if False:", ["tests/unit/test_experimental_ai.py"]),
    ("experimental-execute-refused", "EXPERIMENTAL_EXECUTE=true is refused while nothing is validated",
     "aitrader/service/config.py", "        if experimental_execute:\n", "        if False:\n", ["tests/unit/test_experimental_ai.py"]),
    ("route-shadow", "in DEMO an unvalidated trade is shadow unless explicitly enabled",
     "aitrader/decision/edge_status.py",
     'if mode in ("PAPER", "BACKTEST") or (mode == "DEMO" and experimental_execute):', "if True:",
     ["tests/unit/test_forward.py", "tests/integration/test_forward_service.py"]),
    ("route-unknown-mode", "a mode the build does not know never executes, even a validated edge",
     "aitrader/decision/edge_status.py", 'if mode not in ("PAPER", "BACKTEST", "DEMO"):', "if False:", ["tests/unit/test_forward.py"]),
    ("edge-ai-never-validated", "a model or analogue proposal is never labelled VALIDATED",
     "aitrader/decision/edge_status.py", 'return "EXPERIMENTAL"  # no model or analogue path',
     'return "VALIDATED"  # no model or analogue path', ["tests/unit/test_forward.py", "tests/integration/test_forward_service.py"]),
    ("forward-no-early-bars", "a shadow outcome never uses a bar that opened before the decision",
     "aitrader/learning/forward.py", "keep = (ot >= t0) & (at <= now)", "keep = at <= now", ["tests/unit/test_forward.py"]),
    ("forward-no-future-bars", "a shadow outcome never uses a bar not yet closed",
     "aitrader/learning/forward.py", "keep = (ot >= t0) & (at <= now)", "keep = ot >= t0", ["tests/unit/test_forward.py"]),
    ("forward-stop-first", "a bar touching stop and target counts as a stop",
     "aitrader/learning/forward.py", "            if stop_hit:\n", "            if stop_hit and not tgt_hit:\n", ["tests/unit/test_forward.py"]),
    ("forward-costs", "costs are charged and gross - costs = net",
     "aitrader/learning/forward.py", "cost = (spread + slip + slip_exit + comm) / risk", "cost = 0.0", ["tests/unit/test_forward.py"]),
    ("forward-no-invented-r", "an outcome without data is UNRESOLVED with no R",
     "aitrader/learning/forward.py", '"resolved_at": now, "net_r": None,', '"resolved_at": now, "net_r": 0.0,', ["tests/unit/test_forward.py"]),
    ("lessons-learning-only", "lessons are mined from LEARNING outcomes only",
     "aitrader/learning/taxonomy.py", 'learn = _resolved(rows, "LEARNING", as_of=t)',
     'learn = [r for r in rows if r.get("outcome") and r["outcome"].get("net_r") is not None]', ["tests/unit/test_forward.py"]),
    ("lessons-confirm-later", "a lesson is confirmed only by outcomes resolved after it was created",
     "aitrader/learning/taxonomy.py", 'after=prev["created"]', "after=None", ["tests/unit/test_forward.py"]),
    ("lessons-sample", "one outcome never creates a lesson",
     "aitrader/learning/taxonomy.py", "    if n < MIN_SCOPE_N:\n        return {\"n\": n, \"holds\": None}", "    if n < 1:\n        return {\"n\": n, \"holds\": None}",
     ["tests/unit/test_forward.py"]),
    ("memory-learning-weeks", "the model never reads a trade decided in an EVALUATION week",
     "aitrader/memory/trade_memory.py", 'if opened is not None and partition(int(opened)) != "LEARNING":', "if False:",
     ["tests/integration/test_forward_service.py"]),
    ("eligibility-not-validation", "forward eligibility needs a measured baseline",
     "aitrader/learning/metrics.py", '"pass": baseline_mean is not None and (s.get("avg_r") or 0) > baseline_mean,',
     '"pass": True,', ["tests/unit/test_forward.py"]),
    ("xai-blocking", "a specialist BLOCKING objection is NO_TRADE",
     "aitrader/agents/experimental_ai.py", "    if blocking:\n", "    if False:\n", ["tests/unit/test_experimental_ai.py"]),
    ("xai-specialist-failclosed", "a specialist that did not answer is NO_TRADE",
     "aitrader/agents/experimental_ai.py", "            if not r.ok:\n                return no_trade(f\"specialist",
     "            if False:\n                return no_trade(f\"specialist", ["tests/unit/test_experimental_ai.py"]),
    ("xai-confidence-required", "a model trade must state a confidence in [0, 1]",
     "aitrader/agents/llm_trader.py", "        return \"a trade needs a confidence between 0 and 1\"", "        pass", ["tests/unit/test_llm_trader.py"]),
    ("prompt-no-forcing", "no prompt asks the model to trade because the account is idle",
     "aitrader/agents/llm_trader.py", "Time without a\ntrade costs nothing",
     "The owner does not want the account to sit idle: prefer a small trade to waiting. Time without a\ntrade costs nothing",
     ["tests/unit/test_experimental_ai.py"]),
    # ── edge mission (2026-10): cost ceiling, fix-flow study, trend study ──
    ("risk-cost-to-risk", "the whole round-trip cost (not the spread alone) is capped against the stop",
     "aitrader/risk/engine.py", 'ok &= check("cost_to_risk", cost / stop_dist <= L.max_cost_to_risk,',
     'ok &= check("cost_to_risk", True,', ["tests/unit/test_risk.py"]),
    ("risk-cost-config-ceiling", "configuration can only tighten the cost ceiling",
     "aitrader/service/config.py", 'max_cost_to_risk=min(_f(e, "RISK_MAX_COST_TO_RISK", 0.25), 0.25),',
     'max_cost_to_risk=_f(e, "RISK_MAX_COST_TO_RISK", 0.25),', ["tests/unit/test_risk.py"]),
    ("flow-spread-paid", "a fix-flow trade pays the spread on both fills",
     "aitrader/research/discovery/flow.py", "    entry = em + side * (eh + slip)\n", "    entry = em + side * slip\n",
     ["tests/unit/test_flow.py"]),
    ("flow-exact-bar", "a missing bar is no trade, never the nearest bar",
     "aitrader/research/discovery/flow.py", "        i = self.index.get(int(t))\n        if i is None:\n            return None",
     "        i = self.index.get(int(t))\n        if i is None:\n            i = 0", ["tests/unit/test_flow.py"]),
    ("trend-no-lookahead", "a trend signal reads month-ends up to now only",
     "aitrader/research/discovery/trend.py", "return float(np.sign(month_closes[k] / month_closes[k - 12] - 1.0))",
     "return float(np.sign(month_closes[min(k + 1, len(month_closes) - 1)] / month_closes[k - 12] - 1.0))",
     ["tests/unit/test_trend.py"]),
    ("trend-costs", "trend turnover is charged",
     "aitrader/research/discovery/trend.py", "cost = (turnover * costs.trade_bps / 1e4", "cost = (0.0 * costs.trade_bps / 1e4",
     ["tests/unit/test_trend.py"]),
    ("div1-seal", "the DIV-1 loader truncates at the holdout without a key",
     "scripts/div1.py", "        days = [d for d in days if d < HOLD_START]", "        days = list(days)",
     ["tests/unit/test_trend.py"]),
    ("retail-markup", "an index CFD position pays the broker's markup on its notional",
     "aitrader/research/discovery/retail.py", "f = (-pos * r - abs(pos) * costs.index_markup_pa) / 100.0",
     "f = (-pos * r) / 100.0", ["tests/unit/test_rc.py"]),
    ("retail-unknown-rate", "a position is never held where its financing rate is unknown",
     "aitrader/research/discovery/retail.py", "                if not known:\n                    want = 0.0",
     "                if not known:\n                    pass", ["tests/unit/test_rc.py"]),
    ("rc-tom-window", "the turn-of-month window is days -1..+3, from the calendar",
     "aitrader/research/discovery/rc.py", "for j in cur[-(k_pre + 1):] + nxt[:k_post - 1]:",
     "for j in cur[-k_pre:] + nxt[:k_post]:", ["tests/unit/test_rc.py"]),
    ("rc-fx-lag", "an FX fill uses only fixings published before it", "aitrader/research/discovery/rc.py",
     "FX_LAG = 2", "FX_LAG = 1", ["tests/unit/test_rc.py"]),
    ("rc-xs-next-close", "a cross-sectional decision fills at the next close, never the decision close",
     "aitrader/research/discovery/rc.py", "while di < len(decisions) and decisions[di][0] < j:",
     "while di < len(decisions) and decisions[di][0] <= j:", ["tests/unit/test_rc.py"]),
    ("retail-replication-status", "a replication can never turn a PROMISING retail edge into VALIDATED",
     "aitrader/research/discovery/edges.py", '"VALIDATED": "VALIDATED", "PROMISING_REPLICATED": "PROMISING"}',
     '"VALIDATED": "VALIDATED", "PROMISING_REPLICATED": "VALIDATED"}', ["tests/unit/test_rc.py"]),
    ("tomdiag-markup-split", "the ledger's markup is financing minus the benchmark, not all financing",
     "aitrader/research/discovery/tomdiag.py", '"markup": fin - b,', '"markup": fin,', ["tests/unit/test_tomdiag.py"]),
    ("tomdiag-breakeven", "the break-even cost is the assumed value plus the net's headroom",
     "aitrader/research/discovery/tomdiag.py", "return round(assumed + net_annual / per_unit, 3)",
     "return round(net_annual / per_unit, 3)", ["tests/unit/test_tomdiag.py"]),
    ("tomdiag-ivol-past", "inverse-volatility weights read only returns up to the entry close",
     "aitrader/research/discovery/tomdiag.py", "w = r[k - window:k]", "w = r[k - window + 1:k + 1]",
     ["tests/unit/test_tomdiag.py"]),
    ("intraday-next-open", "an intraday signal decided at a bar's close fills at the next bar's open",
     "aitrader/research/discovery/intraday.py", "j0 = s.i + 1", "j0 = s.i", ["tests/unit/test_intraday.py"]),
    ("intraday-stop-first", "a bar touching both the stop and the target is a stop",
     "aitrader/research/discovery/intraday.py", "if lo <= s.stop:", "if lo <= s.stop and hi < s.target:",
     ["tests/unit/test_intraday.py"]),
    ("intraday-limit-through", "a limit entry fills only when the market trades through it",
     "aitrader/research/discovery/intraday.py", "b.al[j] + w < s.limit", "b.al[j] + w <= s.limit",
     ["tests/unit/test_intraday.py"]),
    ("intraday-gap-exit", "an intraday position closes before a gap of more than an hour",
     "aitrader/research/discovery/intraday.py", "or j == last or b.gap_after[j]:", "or j == last:",
     ["tests/unit/test_intraday.py"]),
    ("intraday-risk-spread", "the risk engine's entry checks see the bar's real spread",
     "aitrader/research/discovery/intraday.py", "spread_now = (b.ao[ei] - b.bo[ei]) * costs.spread_mult",
     "spread_now = 0.0", ["tests/unit/test_intraday.py"]),
    ('opp-walk-forward-exited', 'the engine trains only on trades that exited before the fold',
     'aitrader/research/discovery/opportunity.py', 'tr = np.flatnonzero(train_mask & (t_exit < lo - embargo) & np.isfinite(y))',
     'tr = np.flatnonzero(train_mask & (t_entry < lo) & np.isfinite(y))', ["tests/unit/test_opportunity.py"]),
    ('opp-memory-resolved', 'memory reads only trades resolved before the decision bar',
     'aitrader/research/discovery/opportunity.py', 'cnt = np.searchsorted(ex, np.arange(n), side="left")',
     'cnt = np.searchsorted(ex, np.arange(n) + 12, side="left")', ["tests/unit/test_opportunity.py"]),
    ('opp-flat-by-2055', 'every intraday position is flat by 20:55 UTC',
     'aitrader/research/discovery/opportunity.py', 'out = (b.t[j] + M5 >= deadline[act]) | (j == last[act]) | b.gap_after[j]',
     'out = (j == last[act]) | b.gap_after[j]', ["tests/unit/test_opportunity.py"]),
    ('opp-currency-limit', 'no more than two open positions share a currency',
     'aitrader/research/discovery/opportunity.py', 'if any(sum(1 for _, row in open_ if c in ccys[sym[row]]) >= limits.max_per_currency for c in cq):',
     'if any(sum(1 for _, row in open_ if c in ccys[sym[row]]) > limits.max_per_currency for c in cq):', ["tests/unit/test_opportunity.py"]),
    ('opp-daily-stop', "no new entry after the day's closed trades hit the daily loss limit",
     'aitrader/research/discovery/opportunity.py', 'if day_r.get(int(day[q]), 0.0) <= -limits.daily_stop_r:',
     'if False:', ["tests/unit/test_opportunity.py"]),
    ('opp-htf-completed', 'higher-timeframe ATR uses completed bars only',
     'aitrader/research/discovery/opportunity.py', 'k = np.searchsorted(end_t, b.t + M5, side="right") - 1',
     'k = np.searchsorted(end_t, b.t + 3600, side="right") - 1', ["tests/unit/test_opportunity.py"]),
    ('audit-unvalidated-risk-cap', 'per-trade risk is capped at 0.25% while nothing is validated',
     'aitrader/risk/engine.py', 'pct = min(self.risk_per_trade_pct, HARD_MAX_RISK_PCT, UNVALIDATED_MAX_RISK_PCT)',
     'pct = min(self.risk_per_trade_pct, HARD_MAX_RISK_PCT)', ['tests/unit/test_risk.py']),
    ('audit-weekly-loss', 'the weekly loss limit stops new trades',
     'aitrader/risk/engine.py', 'return Check("weekly_loss", week > -L.weekly_loss_limit_pct,',
     'return Check("weekly_loss", True,', ['tests/unit/test_risk.py']),
    ('audit-unknown-day-start', 'an unknown start-of-day equity fails the daily check',
     'aitrader/risk/engine.py', 'return Check("daily_loss", False, f"start-of-day equity unknown',
     'return Check("daily_loss", True, f"start-of-day equity unknown', ['tests/unit/test_risk.py']),
    ('audit-open-risk', 'total open risk is capped',
     'aitrader/risk/engine.py', 'ok &= check("open_risk", not unknown and open_risk + actual <= eq * L.max_open_risk_pct / 100 + 1e-9,',
     'ok &= check("open_risk", True,', ['tests/unit/test_risk.py']),
    ('audit-data-quality', 'flagged market data is rejected by the risk engine',
     'aitrader/risk/engine.py', 'ok &= check("data_quality", not data_flags,',
     'ok &= check("data_quality", True,', ['tests/unit/test_risk.py']),
    ('audit-model-shadow', "a language model's trade is SHADOW in every mode",
     'aitrader/decision/edge_status.py', '    if ai_originated:\n        return "SHADOW"',
     '    if False:\n        return "SHADOW"', ['tests/unit/test_yahoo_feed.py']),
    ('audit-model-refused-at-execution', "the execution engine refuses a language model's trade",
     'aitrader/execution/engine.py', 'if getattr(decision, "signal_class", None) in MODEL_SIGNAL_CLASSES:',
     'if False:', ['tests/unit/test_execution.py']),
    ('audit-unknown-pauses', 'an order of unknown outcome pauses trading',
     'aitrader/execution/engine.py', 'self._pause(f"order {cid} outcome unknown after an ambiguous broker response: paused until reconciled")',
     'pass', ['tests/unit/test_execution.py']),
    ('audit-tick-value-check', 'a tick value that disagrees with the conversion rate refuses the instrument',
     'aitrader/broker/tradelocker/adapter.py', 'if rate is not None and abs(value / rate - 1) > TICK_VALUE_TOLERANCE:',
     'if False:', ['tests/unit/test_tradelocker_adapter.py']),
    ('audit-config-tighter', 'a risk variable can tighten a limit, never loosen it',
     'aitrader/service/config.py', '            return min(v, ceiling)',
     '            return v', ['tests/integration/test_service.py']),
    ('audit-strict-holdout-t', 'a holdout passed on its sign alone is not a validation',
     'aitrader/research/discovery/edges.py', 'if v == "VALIDATED" and (ht is None or ht < STRICT_HOLDOUT_T):',
     'if False:', ['tests/unit/test_trend.py']),
    ('audit-llm-advisory', "the model's objections are recorded, never applied",
     'aitrader/agents/brain.py', 'decision = self.synth.synthesize(ctx, reports, versions, [])',
     'decision = self.synth.synthesize(ctx, reports, versions, opinions)', ['tests/unit/test_agents.py']),
    ('audit-gate-unmeasured-fails', 'an unmeasured promotion gate fails',
     'aitrader/research/promotion.py', 'ok = v is not None and bool(test(v))',
     'ok = v is None or bool(test(v))', ['tests/unit/test_promotion.py']),
    ("trend-holdout-named", "a trend edge rejected on its holdout says so",
     "aitrader/research/discovery/edges.py", 'if status[hid] == "REJECTED" and h else ()),', 'if False else ()),',
     ["tests/unit/test_trend.py"]),
]


def run_tests(tests: list[str]) -> tuple[bool, float]:
    t0 = time.time()
    # No bytecode is written: a mutant of the same size restored within the same
    # second would otherwise stay cached and silently poison every later run.
    r = subprocess.run([sys.executable, "-B", "-m", "pytest", "-x", "-q", "-p", "no:cacheprovider", *tests],
                       cwd=ROOT, capture_output=True, text=True, env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"})
    return r.returncode == 0, time.time() - t0


def main() -> int:
    rows = []
    for mid, guard, rel, old, new, tests in MUTANTS:
        path = ROOT / rel
        src = path.read_text()
        olds, news = ([old], [new]) if isinstance(old, str) else (old, new)
        counts = [src.count(o) for o in olds]
        if any(c != 1 for c in counts):
            rows.append((mid, guard, rel, "STALE", f"snippets found {counts} times", tests))
            print(mid, "STALE", flush=True)
            continue
        mutated = src
        for o, n in zip(olds, news):
            mutated = mutated.replace(o, n)
        try:
            path.write_text(mutated)
            passed, secs = run_tests(tests)
        finally:
            path.write_text(src)
            for stale in path.parent.glob(f"__pycache__/{path.stem}.*.pyc"):
                stale.unlink()
        verdict = "SURVIVED" if passed else "KILLED"
        rows.append((mid, guard, rel, verdict, f"{secs:.0f}s", tests))
        print(mid, verdict, flush=True)
    killed = sum(r[3] == "KILLED" for r in rows)
    lines = [
        "# Mutation audit",
        "",
        "Each row removes or inverts one safety guard and runs the tests that",
        "should notice. **KILLED** = a test failed, as it must. **SURVIVED** = no",
        "test noticed: the guard is unchecked. Generated by",
        "`python scripts/mutation_audit.py`; the source is restored after each mutant.",
        "",
        f"**{killed} of {len(rows)} killed.**",
        "",
        "| Guard | Where | Result | Tests run |",
        "|---|---|---|---|",
    ]
    for mid, guard, rel, verdict, note, tests in rows:
        lines.append(f"| {guard} (`{mid}`) | `{rel}` | **{verdict}** ({note}) | "
                     + ", ".join(f"`{t.split('/')[-1]}`" for t in tests) + " |")
    (ROOT / "docs" / "MUTATION_AUDIT.md").write_text("\n".join(lines) + "\n")
    return 0 if killed == len(rows) else 1


if __name__ == "__main__":
    raise SystemExit(main())
