"""The canonical research status (takeover audit, step 3).

    python scripts/research_status.py          # -> research_status.json, and the README's generated headline
    python scripts/research_status.py --check  # exit 1 if either is stale (CI / tests)

Every headline number in the README comes from research_status.json, which is built here from what is
committed:

- the research registry (research/registry.jsonl);
- the program artifacts (research/knowledge/*.json);
- the holdout seals;
- the data-quality report;
- the mutation audit;
- the test collection.

Statuses are the strict ones of aitrader/research/promotion.py; a registry PASSED is never copied as
VALIDATED. Curated evidence below cites, for every number, the artifact and key it comes from.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from aitrader.research import promotion  # noqa: E402
from aitrader.risk.engine import RISK_VERSION, UNVALIDATED_MAX_RISK_PCT  # noqa: E402

OUT = ROOT / "research_status.json"
README = ROOT / "README.md"
BEGIN, END = "<!-- research-status:begin (generated by scripts/research_status.py; do not edit) -->", \
    "<!-- research-status:end -->"
STATUS_VERSION = "research-status-1.0.0"


def _artifact(name: str) -> dict:
    p = ROOT / "research" / "knowledge" / f"{name}.json"
    return json.loads(p.read_text()) if p.exists() else {}


def _get(d: Any, *keys: str) -> Any:
    for k in keys:
        if not isinstance(d, dict):
            return None
        d = d.get(k)
    return d


# ── the strategies that ever passed a stage: curated evidence, every value cited ─────────────────────

def curated_evidence() -> dict[str, dict]:
    """Evidence for the strict gates, for every result that a registry verdict, an edge registry entry or a
    document has called PASSED, VALIDATED or PROMISING. Values are read from the artifacts, not typed in."""
    div = _get(_artifact("DIV-2-H"), "results", "DIV2-H1-TSMOM12") or {}
    tom_b = _get(_artifact("RC-EQ2-H"), "results", "RCEQ-E1-TOM") or {}
    tom_a = _get(_artifact("RC-EQ"), "results", "RCEQ-E1-TOM") or {}
    hall = _get(_artifact("RC-EQ2"), "results", "RCEQ2-E8-HALLOWEEN") or {}

    def cost_x2(x):
        return _get(x, "costs_x2", "mean_monthly")

    out = {
        "DIV2-H1-TSMOM12": {
            "label_before_audit": "edge registry VALIDATED (holdout sign rule); registry DIV-2/DIV-2-H PASSED",
            "unit": "monthly portfolio return (not R)",
            "source": "research/knowledge/DIV-2-H.json results.DIV2-H1-TSMOM12",
            "evidence": {
                "min_outcomes": _get(div, "net", "n"),
                # the strategy as THIS system would trade it: retail CFD financing (net before it is +0.19%/month)
                "net_positive": _get(div, "retail_cfd", "mean_monthly"),
                "t_stat": _get(div, "net", "t"),
                "costs_x2_positive": cost_x2(div),
            },
            "notes": ["holdout 2021-01 to 2026-10: net t 0.263, Sharpe 0.11, max drawdown 44%",
                      "at retail CFD financing the holdout return is -5.7% a year (t -0.65)"],
        },
        "RCEQ-E1-TOM": {
            "label_before_audit": "edge registry PROMISING; RC-EQ2-H PASSED (PROMISING_REPLICATED)",
            "unit": "monthly account return at 1x (not R)",
            "source": "research/knowledge/RC-EQ2-H.json results.RCEQ-E1-TOM (universe B, never loaded before) "
                      "and research/knowledge/RC-EQ.json (universe A)",
            "evidence": {
                "min_outcomes": _get(tom_b, "net", "n"),
                "net_positive": _get(tom_b, "net", "mean_monthly"),
                "t_stat": _get(tom_b, "net", "t"),
                "costs_x2_positive": cost_x2(tom_b),
                "delay_positive": _get(tom_b, "delay", "mean_monthly"),
                "first_half_positive": _get(tom_a, "sub", "development", "mean_monthly"),
                "second_half_positive": _get(tom_a, "sub", "validation", "mean_monthly"),
                "no_survivorship": True,
            },
            "failed_preregistered_gates": sorted(set(_get(tom_a, "failed_gates") or []) | set(_get(tom_b, "failed_gates") or [])),
            "notes": [
                f"universe B after all costs: {_get(tom_b, 'net', 'annual_return')} a year, t {_get(tom_b, 'net', 't')}, "
                f"max drawdown {_get(tom_b, 'net', 'max_drawdown')}",
                f"costs x2: t {_get(tom_b, 'costs_x2', 't')}; one-session delay: t {_get(tom_b, 'delay', 't')}",
                f"from 2021: t {_get(tom_b, 'sub', 'from_2021', 't')}; since 2009 (universe A 'modern'): "
                f"t {_get(tom_a, 'sub', 'modern', 't')}",
                f"universe A validation half: t {_get(tom_a, 'sub', 'validation', 't')} after t "
                f"{_get(tom_a, 'sub', 'development', 't')} in development: decayed",
                "every single instrument removed: still positive (leave_one_out, both universes)",
                "without its best year: t 1.68 (B) / 1.82 (A); the best year is 21-22% of the total",
                "UNATTRACTIVE: about 1.9-2.6% a year with a 22-23% maximum drawdown at 1x",
            ],
        },
        "RCEQ2-E8-HALLOWEEN": {
            "label_before_audit": "edge registry PROMISING",
            "unit": "monthly account return (not R)",
            "source": "research/knowledge/RC-EQ2.json results.RCEQ2-E8-HALLOWEEN",
            "evidence": {
                "min_outcomes": _get(hall, "net", "n"),
                "net_positive": _get(hall, "net", "mean_monthly"),
                "t_stat": _get(hall, "net", "t"),
                "costs_x2_positive": cost_x2(hall),
            },
            "failed_preregistered_gates": _get(hall, "failed_gates") or [],
            "notes": [f"RC-EQ2 failed checks: {_get(hall, 'failed_gates')}"],
        },
        "RV-1": {
            "label_before_audit": "registry RV-1 PASSED (stage 1 only)",
            "unit": "information coefficient, then portfolio return",
            "source": "research/knowledge/RV-1-S2.json (stage 2 FAILED)",
            "evidence": {"net_positive": None},
            "notes": ["stage 1 (signal IC) passed; stage 2 (after costs) FAILED, so the program FAILED"],
        },
    }
    return out


def strict_status_of_edge(edge_id: str, cur: dict) -> tuple[str, list[str]]:
    c = cur.get(edge_id)
    if c is None:
        return "FAILED", ["rejected by its program"]
    if edge_id == "RV-1":
        return "FAILED", c["notes"]
    # A preregistered robustness gate it failed (anything but significance, which the strict t gate judges
    # again) is a failure, whatever the edge registry called it.
    robust = [g for g in c.get("failed_preregistered_gates", []) if g != "t"]
    if robust:
        return "FAILED", [f"failed its preregistered gates: {', '.join(robust)}"]
    return promotion.status(c["evidence"])


# ── assembly ──────────────────────────────────────────────────────────────────────────────────────────

def _git(*args) -> str:
    try:
        return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def _sha(paths) -> str:
    h = hashlib.sha256()
    for p in paths:
        h.update(p.read_bytes())
    return h.hexdigest()[:16]


def _tests() -> dict:
    r = subprocess.run([sys.executable, "-m", "pytest", "--collect-only", "-q", "-p", "no:cacheprovider", "tests"],
                       cwd=ROOT, capture_output=True, text=True)
    m = re.search(r"(\d+) tests? collected", r.stdout)
    per_file = [int(x) for x in re.findall(r"^tests/\S+: (\d+)$", r.stdout, flags=re.M)]
    n = int(m.group(1)) if m else (sum(per_file) if per_file else None)
    return {"collected": n, "command": "python -m pytest tests"}


def _mutation() -> dict:
    p = ROOT / "docs" / "MUTATION_AUDIT.md"
    m = re.search(r"\*\*(\d+) of (\d+) killed\.\*\*", p.read_text()) if p.exists() else None
    return {"killed": int(m.group(1)), "total": int(m.group(2)), "command": "python scripts/mutation_audit.py"} \
        if m else {"killed": None, "total": None}


def build(with_tests: bool = True) -> dict:
    rows = [json.loads(line) for line in (ROOT / "research" / "registry.jsonl").read_text().splitlines() if line.strip()]
    trials = {r["id"]: r for r in rows if r["kind"] == "trial"}
    verdicts = {r["trial"]: r for r in rows if r["kind"] == "verdict"}
    cur = curated_evidence()
    experiments = []
    for tid, t in trials.items():
        v = verdicts.get(tid)
        raw = (v or {}).get("status") or t.get("status")
        if tid in ("RV-1",):
            st, why = "FAILED", cur["RV-1"]["notes"]
        elif tid in ("DIV-2", "DIV-2-H"):
            st, why = strict_status_of_edge("DIV2-H1-TSMOM12", cur)
        elif tid == "RC-EQ2-H":
            st, why = strict_status_of_edge("RCEQ-E1-TOM", cur)
        elif v is None and raw == "PENDING":
            st, why = "REGISTERED", ["no verdict (descriptive or forward-only)" if t.get("tests") == 0 or tid == "TOM-F"
                                     else "no verdict"]
        elif raw in ("FAILED", "ABANDONED", "INCONCLUSIVE"):
            st, why = "FAILED", [f"registry verdict {raw}"]
        else:
            st, why = "FAILED", [f"registry verdict {raw}: not examined against the strict gates"]
        experiments.append({
            "experiment_id": tid, "title": t.get("title"), "hypothesis": t.get("hypothesis"),
            "preregistration": t.get("preregistration"), "registered": t.get("registered"),
            "uses": t.get("uses"), "tests": t.get("tests"), "configurations": t.get("configurations"),
            "design": t.get("design"), "registry_verdict": raw, "status": st, "status_reasons": why,
            "artifact": (v or {}).get("result", {}).get("artifact"),
            "artifact_sha256": (v or {}).get("result", {}).get("artifact_sha256"),
        })
    edges = json.loads((ROOT / "research" / "knowledge" / "edge_registry.json").read_text())["edges"]
    edge_rows = []
    for e in edges:
        st, why = strict_status_of_edge(e["edge_id"], cur) if e["edge_id"] in cur else \
            ("FAILED", [f"edge registry {e['status']}: " + ", ".join(e.get("failed_checks") or [])])
        edge_rows.append({"edge_id": e["edge_id"], "program": e["program"], "registry_status": e["status"],
                          "status": st, "reasons": why, "net_expectancy": e.get("net_expectancy"),
                          "t_stat": e.get("t_stat"), "sample_size": e.get("sample_size"), "source": e.get("source")})
    dq_path = ROOT / "research" / "results" / "data_quality.json"
    dq = json.loads(dq_path.read_text()) if dq_path.exists() else {}
    holdouts = []
    for p in sorted((ROOT / "research").glob("holdout*.json")):
        h = json.loads(p.read_text())
        touching = [x for x in experiments
                    if any(u.get("universe") == h["universe"] and str(u.get("end") or "9999") > h["start"][:10]
                           and str(u.get("start", "")) >= h["start"][:10] for u in (x.get("uses") or []))]
        opened = [x["experiment_id"] for x in touching if str(x.get("registered") or "") >= h["sealed_at"]]
        prior = [x["experiment_id"] for x in touching if str(x.get("registered") or "") < h["sealed_at"]]
        holdouts.append({"file": str(p.relative_to(ROOT)), "universe": h["universe"], "start": h["start"],
                         "sealed_at": h["sealed_at"], "opened_by": opened, "exposure_before_seal": prior,
                         "state": "OPENED" if opened else "SEALED"})
    validated = [e for e in edge_rows if e["status"] == "VALIDATED"]
    promising = [e for e in edge_rows if e["status"] in ("PROMISING", "FORWARD_TESTING", "ELIGIBLE_FOR_REVIEW")]
    counts = {s: sum(1 for x in experiments if x["status"] == s) for s in promotion.STATUSES}
    edge_counts = {s: sum(1 for x in edge_rows if x["status"] == s) for s in promotion.STATUSES}
    # The final status says whether anything PASSED: a PROMISING lead has not, so it is still NO EDGE
    # (with the leads listed under promising_edges).
    eligible = [e for e in edge_rows if e["status"] == "ELIGIBLE_FOR_REVIEW"]
    final = "VALIDATED" if validated else ("ELIGIBLE FOR REVIEW" if eligible else "NO EDGE")
    return {
        "status_version": STATUS_VERSION, "promotion_version": promotion.PROMOTION_VERSION,
        "code_commit": _git("rev-parse", "HEAD"),
        "data_version": "bars-" + _sha(sorted((ROOT / "data").glob("*manifest*.json")) +
                                       sorted((ROOT / "data" / "m5").glob("manifest_*.json"))),
        "cost_model_version": {
            "research_h1": "labels.CostModel: measured bid/ask, 0.1 pip slippage per fill, 0.7 pip commission, "
                           "swap 0.05 x ATR24(H1) per night either side",
            "intraday": "intraday.Costs (id-1.0.0): measured bid/ask, 0.1 pip slippage, 0.7 pip commission, BIS financing "
                        "per 21:00 UTC rollover (Wednesday x3) with 1.5% markup",
            "retail_cfd": "retail.py / rc.py: spread, slippage, overnight markup, dividends (RC programs)",
            "paper_broker": "paper-1.1.0: live bid/ask + 0.1 pip slippage, $7/lot commission, swap per 21:00 UTC rollover",
            "risk_engine": RISK_VERSION,
            "provisional": "no broker is integrated (PAPER only; MetaTrader 5 planned): every research cost is "
                           "provisional against the broker that will eventually be used",
        },
        "generated_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "final_status": final,
        "final_statement": ("NO EDGE — DO NOT TRADE" if final == "NO EDGE" else
                            "ELIGIBLE FOR REVIEW — NOT VALIDATED, DO NOT TRADE" if final == "ELIGIBLE FOR REVIEW" else final),
        "experiment_counts": counts, "edge_counts": edge_counts,
        "experiments": experiments,
        "strategies": [
            {"strategy": "evidence (analogue synthesis, PR-001 system)", "status": "FAILED",
             "reason": "PR-001 FAILED: -0.07R per trade after costs, t -2.9 (2010-2016)", "route": "PAPER only"},
            {"strategy": "llm_trader / trading_room / experimental_ai (a language model proposes)", "status": "PROPOSED",
             "reason": "never backtestable; no forward evidence of value", "route": "SHADOW in every mode (takeover audit)"},
            {"strategy": "edges (promoted edges only)", "status": "REGISTERED",
             "reason": "models/artifacts/promoted_edges.json absent: nothing promoted", "route": "nothing to trade"},
            {"strategy": "turn-of-the-month on index CFDs (RCEQ-E1-TOM)",
             "status": strict_status_of_edge("RCEQ-E1-TOM", cur)[0],
             "reason": "research only; not implemented in the bot; see promising_edges", "route": "not implemented"},
            {"strategy": "ID-2 intraday opportunity engine", "status": "FAILED",
             "reason": "0 of 30 tests promoted on development 2011-2013", "route": "research only"},
        ],
        "validated_edges": validated,
        "promising_edges": [{**e, "curated": cur.get(e["edge_id"])} for e in promising],
        "failed_edges": [{"edge_id": e["edge_id"], "program": e["program"], "reasons": e["reasons"][:3]}
                         for e in edge_rows if e["status"] == "FAILED"],
        "sealed_periods": holdouts,
        "known_data_defects": [
            {"defect": "00:00-00:59 UTC missing", "files": dq.get("hour00_missing_files"),
             "measured_bias_r": (dq.get("hour00_sensitivity") or {}).get("max_abs_difference_r"),
             "rerun": "impossible here: no source with the hour is reachable (docs/DATA_QUALITY_REPORT.md)"},
            {"defect": "index-CFD bid/ask history only from 2012 (Dukascopy datafeed), sparse quoting in 2012-2013",
             "files": "data/ix/", "measured_bias_r": None,
             "rerun": "IX programs use 2012+; days without a quote are skipped, never filled"},
        ],
        "known_research_limitations": [
            "no broker is integrated (PAPER only): real spreads, commission and swaps of the eventual broker are "
            "unmeasured; all costs are provisional",
            "index-CFD spreads are roughly constant in points, so their cost in bp fell 3-5x from 2013 to 2020 as the "
            "indices rose: results from early years overstate today's cost",
            "FX bid/ask history is 2007-2016 for research (2017+ sealed); about 10 years, one source",
            "a language model cannot be backtested (training data contains the outcomes): its value is forward-only",
            "every rejected hypothesis was judged on overlapping FX data; thresholds count prior tests (registry)",
            "the forward ledger has no resolved EVALUATION outcomes in this repository: no forward evidence exists",
        ],
        "risk_policy": {"live_risk_pct": 0.0, "max_risk_per_trade_pct_while_unvalidated": UNVALIDATED_MAX_RISK_PCT,
                        "experimental_execute": "refused", "model_originated_trades": "SHADOW",
                        "llm_veto": "advisory only (recorded as would_veto for the A/B comparison)"},
        "tests": _tests() if with_tests else None,
        "mutation_audit": _mutation(),
    }


def headline(st: dict) -> str:
    c, e = st["experiment_counts"], st["edge_counts"]
    tom = next((p for p in st["promising_edges"] if p["edge_id"] == "RCEQ-E1-TOM"), None)
    lines = [
        BEGIN,
        f"> **Canonical status ({st['status_version']}, from `research_status.json`): {st['final_statement']}.**",
        f"> - Experiments: {len(st['experiments'])} registered; "
        + ", ".join(f"{k} {c[k]}" for k in promotion.STATUSES if c.get(k)) + ".",
        f"> - Edges: {sum(e.values())} recorded; " + ", ".join(f"{k} {e[k]}" for k in promotion.STATUSES if e.get(k))
        + ". VALIDATED requires every gate in `aitrader/research/promotion.py`; none passes.",
    ]
    if tom:
        lines.append("> - The one PROMISING lead (not a pass), turn-of-the-month on index CFDs, is **unattractive and decayed**: "
                     "about 1.9% a year at t 2.18 with a 23% drawdown, t 0.46 since 2021, t 0.64 at doubled costs. "
                     "It is not implemented.")
    lines += [
        f"> - Live trading is impossible; DEMO sends no order (nothing is validated); per-trade risk is capped at "
        f"{st['risk_policy']['max_risk_per_trade_pct_while_unvalidated']}%. Language-model trades are shadow only.",
        f"> - Tests collected: {(st.get('tests') or {}).get('collected')}; mutation audit: "
        f"{st['mutation_audit'].get('killed')} of {st['mutation_audit'].get('total')} killed. "
        "Numbers in older reports are snapshots of their date.",
        "> - Defects, patches, tests and the strategy-by-strategy record: docs/TAKEOVER_AUDIT.md.",
        END,
    ]
    return "\n".join(lines)


def write_readme(st: dict) -> str:
    text = README.read_text()
    block = headline(st)
    if BEGIN in text:
        a, b = text.index(BEGIN), text.index(END) + len(END)
        return text[:a] + block + text[b:]
    first = text.index("\n> **Status:")
    return text[:first] + "\n" + block + "\n>" + text[first:]


def _stable(st: dict) -> dict:
    return {k: v for k, v in st.items() if k not in ("generated_at_utc", "code_commit")}


def main() -> int:
    check = "--check" in sys.argv
    st = build(with_tests=True)
    if check:
        old = json.loads(OUT.read_text()) if OUT.exists() else {}
        stale_json = _stable(old) != _stable(st)
        stale_readme = headline(old) not in README.read_text() if old else True
        print(json.dumps({"research_status_stale": stale_json, "readme_stale": stale_readme}))
        return 1 if (stale_json or stale_readme) else 0
    OUT.write_text(json.dumps(st, indent=1, sort_keys=True, default=str) + "\n")
    README.write_text(write_readme(st))
    print(json.dumps({"final": st["final_statement"], "experiments": st["experiment_counts"],
                      "edges": st["edge_counts"]}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
